{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "youerdev",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101343560,
          "sha512": "e1d497b24e4f643da2e4aa2eccde84cdd9d7c6bbfcc6cd8d9205ce83d406b081bcfac9179ab8853e9e16148e4a019099011c302ee4827d8fd161989304edca01",
          "sha256": "2cabb149bcd03b9f4ac38258b0d8329b8291ecdc20a740ec1345f95bca7ac8ce",
          "sha1": "53739e36539ae75ccb68fc9564f366ffcb6aad09",
          "md5": "93c01c16d6ec86d28475501ee44f720c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101343560,
          "sha512": "e1d497b24e4f643da2e4aa2eccde84cdd9d7c6bbfcc6cd8d9205ce83d406b081bcfac9179ab8853e9e16148e4a019099011c302ee4827d8fd161989304edca01",
          "sha256": "2cabb149bcd03b9f4ac38258b0d8329b8291ecdc20a740ec1345f95bca7ac8ce",
          "sha1": "53739e36539ae75ccb68fc9564f366ffcb6aad09",
          "md5": "93c01c16d6ec86d28475501ee44f720c"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101343560,
          "sha512": "e1d497b24e4f643da2e4aa2eccde84cdd9d7c6bbfcc6cd8d9205ce83d406b081bcfac9179ab8853e9e16148e4a019099011c302ee4827d8fd161989304edca01",
          "sha256": "2cabb149bcd03b9f4ac38258b0d8329b8291ecdc20a740ec1345f95bca7ac8ce",
          "sha1": "53739e36539ae75ccb68fc9564f366ffcb6aad09",
          "md5": "93c01c16d6ec86d28475501ee44f720c"
        }
      ]
    }
  ]
}
