{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc",
    "module": "youerdev",
    "version": "1.21.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.0.0"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101427195,
          "sha512": "fa21476aa4483e038d24eabba394ade80f32cab5fc3a7794f75c62ce5282f7dd6a72e66becc3186824fa5da5665532b520393fc98d1deeb0ee3b7377bcf1cedf",
          "sha256": "cca64afa548cb163cc97d2854b1d0b81f83654a63f760f068158f9069325bb02",
          "sha1": "d69a42c1958d084bcf991d46c8c4efe39c95ae75",
          "md5": "8bd2c0547055567a17a0a7f71a81e357"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101427195,
          "sha512": "fa21476aa4483e038d24eabba394ade80f32cab5fc3a7794f75c62ce5282f7dd6a72e66becc3186824fa5da5665532b520393fc98d1deeb0ee3b7377bcf1cedf",
          "sha256": "cca64afa548cb163cc97d2854b1d0b81f83654a63f760f068158f9069325bb02",
          "sha1": "d69a42c1958d084bcf991d46c8c4efe39c95ae75",
          "md5": "8bd2c0547055567a17a0a7f71a81e357"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "youerdev-1.21.1.jar",
          "url": "youerdev-1.21.1.jar",
          "size": 101427195,
          "sha512": "fa21476aa4483e038d24eabba394ade80f32cab5fc3a7794f75c62ce5282f7dd6a72e66becc3186824fa5da5665532b520393fc98d1deeb0ee3b7377bcf1cedf",
          "sha256": "cca64afa548cb163cc97d2854b1d0b81f83654a63f760f068158f9069325bb02",
          "sha1": "d69a42c1958d084bcf991d46c8c4efe39c95ae75",
          "md5": "8bd2c0547055567a17a0a7f71a81e357"
        }
      ]
    }
  ]
}
