{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.fancymodloader",
    "module": "junit-fml",
    "version": "4.0.44",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "junit-fml-4.0.44.jar",
          "url": "junit-fml-4.0.44.jar",
          "size": 3722,
          "sha512": "7f134036ccfeffa729b5babafc90a4c40157551c26e52e820677f5f8ffbed841942ef7fe6b9b706dedab7fda20ab9adc46af127ea0f57b37c11c644db86f289d",
          "sha256": "83d81575dcde5b61c0ea043bb00a6720c3a6b63304bdf96391a14cd9d002ca5f",
          "sha1": "0c30592fe7c768c2275c699a82b371d5a70bbc68",
          "md5": "22d82c1436066ab11bfee512172a2dfe"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        }
      ],
      "files": [
        {
          "name": "junit-fml-4.0.44.jar",
          "url": "junit-fml-4.0.44.jar",
          "size": 3722,
          "sha512": "7f134036ccfeffa729b5babafc90a4c40157551c26e52e820677f5f8ffbed841942ef7fe6b9b706dedab7fda20ab9adc46af127ea0f57b37c11c644db86f289d",
          "sha256": "83d81575dcde5b61c0ea043bb00a6720c3a6b63304bdf96391a14cd9d002ca5f",
          "sha1": "0c30592fe7c768c2275c699a82b371d5a70bbc68",
          "md5": "22d82c1436066ab11bfee512172a2dfe"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-fml-4.0.44-sources.jar",
          "url": "junit-fml-4.0.44-sources.jar",
          "size": 2949,
          "sha512": "925832b99447997e142745114728a3cda8ef84a4e648fa89332be2b7ba7e50b096f882fca1f0b4e9de464da461b580a1f3c07d49a4b91bb7084beb6eff3833ee",
          "sha256": "48058e062aef64689424ee5518da4724d7630ca2c9b5f09274b21a0d05b730c5",
          "sha1": "6afd0c591265e1976de1d8397ef257204e81df31",
          "md5": "bab40d373b472581b6db5764a2ce8d2c"
        }
      ]
    }
  ]
}
