{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mohistmc.fancymodloader",
    "module": "junit-fml",
    "version": "4.0.43",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "junit-fml-4.0.43.jar",
          "url": "junit-fml-4.0.43.jar",
          "size": 3722,
          "sha512": "ee37f738b58da545b1f971efc703c13e6db09e1d15d76b29b20a5365caf73425d191093c74a5b4f6c113bbe8dde113f3e1369cc9aa64457656215aa99269b1fe",
          "sha256": "cfa2fba9ac8c790e1dea9cb932b1e067eda7d881dd71b49653f31fdbc85e2c15",
          "sha1": "590bdec479b7edd68366ea935ca369fbaacd55bc",
          "md5": "1ea8c4954c292d8b1c6f8b0d4bfd83f1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.junit",
          "module": "junit-bom",
          "version": {
            "requires": "5.10.2"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher"
        }
      ],
      "files": [
        {
          "name": "junit-fml-4.0.43.jar",
          "url": "junit-fml-4.0.43.jar",
          "size": 3722,
          "sha512": "ee37f738b58da545b1f971efc703c13e6db09e1d15d76b29b20a5365caf73425d191093c74a5b4f6c113bbe8dde113f3e1369cc9aa64457656215aa99269b1fe",
          "sha256": "cfa2fba9ac8c790e1dea9cb932b1e067eda7d881dd71b49653f31fdbc85e2c15",
          "sha1": "590bdec479b7edd68366ea935ca369fbaacd55bc",
          "md5": "1ea8c4954c292d8b1c6f8b0d4bfd83f1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "junit-fml-4.0.43-sources.jar",
          "url": "junit-fml-4.0.43-sources.jar",
          "size": 2949,
          "sha512": "b9b80f193ee36fdafd7c0429ccfd61b81aaecd2b016dea453e9968086f46994e216f6b114f782543d17b3beda677e741cb05897b0518ba2baad43f6785ca775d",
          "sha256": "0db3303d3a4abf7ca30bb01b3854cda46998ade8f85169515cd9cc842d777bec",
          "sha1": "7fb266be9a54b1d62876de365730cbee51d8cdee",
          "md5": "330c82c95aa36c4efde438d2b71027df"
        }
      ]
    }
  ]
}
